import { useRef } from "react";

type Values = Record<string, string | boolean>;
type Save = (key: string, value: string | boolean) => void;

function Field({ id, label, values, onChange, type = "text" }: { id: string; label: string; values: Values; onChange: Save; type?: string }) {
  const key = `learner-workbook.${id}`;
  return <input type={type} aria-label={label} defaultValue={String(values[key] ?? "")} onBlur={event => onChange(key, event.target.value)} />;
}

function Tick({ id, label, values, onChange }: { id: string; label: string; values: Values; onChange: Save }) {
  const key = `learner-workbook.${id}`;
  return <input type="checkbox" aria-label={label} defaultChecked={values[key] === true} onChange={event => onChange(key, event.target.checked)} />;
}

function Lines({ id, count, values, onChange, label }: { id: string; count: number; values: Values; onChange: Save; label: string }) {
  const refs = useRef<Array<HTMLInputElement | null>>([]);
  return <div className="lw-lines">{Array.from({ length: count }, (_, index) => {
    const key = `learner-workbook.${id}.line-${index + 1}`;
    return <input key={key} ref={node => { refs.current[index] = node; }} aria-label={`${label}, line ${index + 1}`} defaultValue={String(values[key] ?? "")} onBlur={event => onChange(key, event.target.value)} onKeyDown={event => { if (event.key === "Enter") { event.preventDefault(); refs.current[index + 1]?.focus(); } }} />;
  })}</div>;
}

function Page({ number, children, className = "" }: { number: number; children: React.ReactNode; className?: string }) {
  return <section className={`lw-page ${className}`} data-page={number}>{children}</section>;
}

const outcomes = [
  { no: 1, title: "Set up user access to a local area computer network.", points: ["The explanation identifies resources whose access can be managed.", "The explanation outlines the level of access for different categories of people.", "The explanation outlines methods of controlling access.", "The explanation outlines the purpose of an access audit trail."], question: <>Write notes on the following:<br />• AUDIT TRAILS<br />• Network access control (NAC)<br />• Resources or physical components of LAN</>, mark: 10, pages: [18, 24] },
  { no: 2, title: "Explain local area computer network performance issues.", points: ["The explanation describes a range of factors that affects response times on a LAN.", "The explanation outlines the need to analyse data and identify problems.", "The explanation outlines how diagnostic tools are used to collect data.", "The explanation outlines and compares methods for improving performance."], question: "Explain local area computer network performance issues.", mark: 5, pages: [18, 24] },
  { no: 3, title: "Explain local area computer network support issues.", points: ["The explanation distinguishes sources.", "The explanation outlines user expectations of a range of support options."], question: "Explain local area computer network support issues.", mark: 5, pages: [21] },
  { no: 4, title: "Explain typical viruses on local area computer networks.", points: ["The explanation outlines the symptoms and transmission of viruses.", "The explanation allows the selection of a method for the prevention, detection, and eradication of viruses for a situation."], question: "Explain typical viruses on local area computer networks.", mark: 5, pages: [21] },
];

function OutcomeHeader({ outcome }: { outcome: typeof outcomes[number] }) {
  return <><div className="lw-outcome-head"><strong>SPECIFIC OUTCOME {outcome.no}.</strong><b>{outcome.title}</b><span>Learning Outcomes</span><ol>{outcome.points.map(point => <li key={point}>{point}</li>)}</ol></div><table className="lw-table lw-question"><thead><tr><th>Activity</th><th>Questions Description</th><th>Mark</th></tr></thead><tbody><tr><td>{outcome.no}</td><td>{outcome.question}</td><td>{outcome.mark}</td></tr></tbody></table></>;
}

export function LearnerWorkbook({ values, onChange }: { values: Values; onChange: Save }) {
  const field = (id: string, label: string, type?: string) => <Field id={id} label={label} type={type} values={values} onChange={onChange} />;
  const inlineField = (id: string, label: string, type?: string) => <span className="lw-inline-field">{field(id, label, type)}</span>;
  return <div className="lw-document">
    <Page number={1} className="lw-cover"><div className="lw-cover-main"><img src="/logos/eruditio.svg" alt="Eruditio" /><div className="lw-cover-panel"><h1>DEMONSTRATE AN UNDERSTANDING OF ISSUES AFFECTING THE MANAGEMENT OF A LOCAL AREA COMPUTER NETWORK (LAN)</h1><div className="lw-cover-meta"><b>UNIT STANDARD 114046</b><b>NQF LEVEL: 5</b><b>CREDITS: 4</b><b>NOTIONAL HOURS: 40</b></div><table className="lw-table lw-cover-table"><thead><tr><th colSpan={2}>LEARNER INFORMATION</th></tr></thead><tbody>{[["cover-name","Name"],["cover-surname","Surname"],["cover-id","ID Number"],["cover-contact","Contact"]].map(([id,label])=><tr key={id}><th>{label}</th><td>{field(id,label)}</td></tr>)}</tbody></table></div></div><aside>LEARNER WORKBOOK</aside></Page>

    <Page number={2}><h2 className="lw-centre">Learner Information:</h2><table className="lw-table lw-details"><thead><tr><th>Details</th><th>Please Complete this Section</th></tr></thead><tbody>{[["name","Name & Surname"],["organisation","Organisation"],["unit-dept","Unit/Dept"],["facilitator","Facilitator Name"],["date-started","Date Started"],["date-completed","Date of Completion"]].map(([id,label])=><tr key={id}><th>{label}:</th><td>{field(id,label,/date/i.test(label)?"date":undefined)}</td></tr>)}</tbody></table><div className="lw-copy"><h3>Copyright</h3><p>All rights reserved. The copyright of this document, its previous editions and any annexures thereto, is protected and expressly reserved. No part of this document may be reproduced, stored in a retrievable system, or transmitted, in any form or by any means, electronic, mechanical, photocopying, recording or otherwise without the prior permission.</p></div><table className="lw-table lw-overview lw-overview-gap"><thead><tr><th colSpan={2}>OVERVIEW</th></tr></thead><tbody><tr><th>About the Learner Workbook</th><td>This Learner Exercise Workbook has been designed and developed to evaluate learners’ level of understanding. It forms part of a series of Learner Workbooks developed for the National Certificate: Information Technology: Systems Support, SAQA 48573, Level 5, 147 credits.</td></tr><tr><th>Purpose</th><td>The purpose of this Learner Exercise Workbook is to evaluate learners’ understanding of the specific outcomes and assessment criteria of the registered unit standard.</td></tr></tbody></table><table className="lw-table lw-us-table"><thead><tr><th>US No</th><th>US Title</th><th>Level</th><th>Credits</th></tr></thead><tbody><tr><td>SAQA 114046</td><td>Demonstrate an understanding of issues affecting the management of a local area computer network (LAN)</td><td>5</td><td>4</td></tr></tbody></table></Page>

    <Page number={3}><table className="lw-table lw-instructions"><tbody><tr><th>Context</th><td>This assessment represents the Formative Assessment component and should be completed in the classroom/training room.</td></tr><tr><th>Resources</th><td>The following resources are needed:<ol><li>Learner Guide</li><li>Assessment Preparation</li></ol></td></tr><tr><th>Instructions to Facilitators</th><td>Explain completion of the workbook to each learner and interview the learner on similar questions should they not be able to write.</td></tr><tr><th>Instructions to Learners</th><td><ul><li>Complete the workbook as per the instructions.</li><li>Ensure all questions are completed.</li><li>Ensure the work is your own.</li><li>Attach and clearly reference all annexures.</li></ul></td></tr><tr><th>Assessment Time</th><td>Learners are required to complete this assessment within the allocated time frame.</td></tr><tr><th>Total Marks</th><td>This formative assessment carries a total mark of <span className="lw-inline-group">{inlineField("total-marks","Total marks")} points.</span> To meet the pass mark, learners must achieve <span className="lw-inline-group">{inlineField("pass-mark","Pass mark")}.</span></td></tr><tr><th>Equipment</th><td>Learners are required to have a pen and pencil, ruler, and exam pad or additional paper.</td></tr></tbody></table></Page>

    <Page number={4} className="lw-workshop-page"><h3>GENERAL INFORMATION</h3><div className="lw-bar">LEARNER DETAILS</div><table className="lw-table lw-details"><tbody>{[["full-names","Learner Full Names"],["learner-number","Learner ID No."],["org-2","Organisation"],["dept-2","Unit/Dept"]].map(([id,label])=><tr key={id}><th>{label}:</th><td colSpan={3}>{field(id,label)}</td></tr>)}<tr><th>Contact Details:</th><th>Telephone /Cell Numbers:</th><th colSpan={2}>Email Address:</th></tr><tr><td></td><td>{field("telephone","Telephone","tel")}</td><td colSpan={2}>{field("email","Email","email")}</td></tr><tr className="lw-grey"><th colSpan={4}>WORKSHOP DETAILS</th></tr>{[["venue","Workshop Venue"],["facilitator-2","Facilitator Name"],["started-2","Date Started"],["completed-2","Date Completed"]].map(([id,label])=><tr key={id}><th>{label}:</th><td colSpan={3}>{field(id,label,/Date/.test(label)?"date":undefined)}</td></tr>)}</tbody></table><table className="lw-table lw-checklist"><thead><tr><th>ASSESSMENT PREPARATION CHECKLIST<br />DESCRIPTION</th><th>YES</th><th>NO</th><th>COMMENTS/CONTINGENCY</th></tr></thead><tbody>{["This assessment is a formative assessment based on the outlined unit standard.","Your assessment evidence needs to be submitted on the agreed date and at the agreed place.","You will be assessed based on the outlined Unit Standards and linked assessment criteria.","The assessment methods and competence requirements have been explained."].map((text,index)=><tr key={text}><td>{text}</td><td><Tick id={`prep.${index}.yes`} label={`${text} yes`} values={values} onChange={onChange}/></td><td><Tick id={`prep.${index}.no`} label={`${text} no`} values={values} onChange={onChange}/></td><td>{field(`prep.${index}.comment`,`${text} comment`)}</td></tr>)}{["To meet the formative assessment pass mark, you should obtain at least 80%.","Detailed written and verbal feedback will be provided.","If declared not yet competent, you will receive reassessment opportunities.","You may lodge an appeal if dissatisfied with the assessment decision.","Assessment results and portfolio information remain confidential."].map((text,index)=><tr key={text}><td>{text}</td><td><Tick id={`prep2.${index}.yes`} label={`${text} yes`} values={values} onChange={onChange}/></td><td><Tick id={`prep2.${index}.no`} label={`${text} no`} values={values} onChange={onChange}/></td><td>{field(`prep2.${index}.comment`,`${text} comment`)}</td></tr>)}</tbody></table></Page>

    <Page number={5} className="lw-declaration-page"><div className="lw-bar">Learner’s Declaration</div><p>I, {field("declaration-name","Learner declaration name")}, hereby declare that I am ready for the assessment, have reviewed the assessment preparation and plan, understand the assessment process, and am happy that it will be conducted fairly.</p><table className="lw-table lw-sign"><tbody><tr><th>Learner Signature</th><td>{field("declaration-signature","Learner signature")}</td><th>Date</th><td>{field("declaration-date","Declaration date","date")}</td><th>Facilitator Signature</th><td>{field("declaration-facilitator","Facilitator signature")}</td></tr></tbody></table><div className="lw-unit-title lw-unit-inline"><div><b>Demonstrate an understanding of issues affecting the management of a local area computer network (LAN)</b><h1>Learning Unit 1</h1><dl><dt>UNIT STANDARD NUMBER</dt><dd>114046</dd><dt>LEVEL ON THE NQF</dt><dd>5</dd><dt>CREDITS</dt><dd>4</dd><dt>FIELD</dt><dd>Physical, Mathematical, Computer and Life Sciences</dd><dt>SUB FIELD</dt><dd>Information Technology and Computer Sciences</dd></dl></div><div className="lw-purpose"><b>PURPOSE:</b><ul><li>This unit standard provides conceptual knowledge of the areas covered.</li><li>It is for those working in or entering Data Communications &amp; Networking.</li><li>Explain management of access to a LAN.</li><li>Explain LAN performance issues.</li><li>Explain LAN support issues.</li><li>Explain typical viruses on LANs.</li></ul><b>LEARNING ASSUMED TO BE IN PLACE:</b><p>The credit value assumes prior knowledge and skills in local area networks, computer network principles, and supporting users of a LAN.</p></div></div></Page>

    {outcomes.flatMap((outcome, outcomeIndex) => outcome.pages.map((lineCount, pageIndex) => <Page key={`${outcome.no}-${pageIndex}`} number={6 + outcomes.slice(0,outcomeIndex).reduce((n,item)=>n+item.pages.length,0)+pageIndex}>{pageIndex === 0 && <OutcomeHeader outcome={outcome}/>}<Lines id={`outcome-${outcome.no}.page-${pageIndex+1}`} count={lineCount} label={`Specific outcome ${outcome.no} answer`} values={values} onChange={onChange}/></Page>))}

    <Page number={12}><div className="lw-bar">SELF-ASSESSMENT</div><p>The learner must use this self-evaluation checklist to rate their mastery of the learning outcomes.</p><ol><li>Not able to comply</li><li>Reasonable compliance</li><li>Able to comply fully</li></ol><table className="lw-table lw-self"><thead><tr><th>LEARNING OUTCOMES</th><th>1</th><th>2</th><th>3</th></tr></thead><tbody>{Array.from({length:7},(_,index)=><tr key={index}><td>{index+1}</td>{[1,2,3].map(score=><td key={score}><Tick id={`self.${index+1}.${score}`} label={`Learning outcome ${index+1}, rating ${score}`} values={values} onChange={onChange}/></td>)}</tr>)}</tbody></table><div className="lw-sign-lines"><label>Learner Signature {field("self-learner-signature","Learner signature")}</label><label>Date {field("self-learner-date","Learner date","date")}</label><label>Facilitator’s Signature {field("self-facilitator-signature","Facilitator signature")}</label><label>Date {field("self-facilitator-date","Facilitator date","date")}</label></div><div className="lw-bar">ASSESSMENT FEEDBACK REPORT</div><h3>FACILITATOR FEEDBACK &amp; REMARKS</h3><Lines id="facilitator-feedback" count={5} label="Facilitator feedback and remarks" values={values} onChange={onChange}/></Page>

    <Page number={13} className="lw-final-page"><div className="lw-bar">ASSESSMENT JUDGMENT</div><div className="lw-judgment"><div className="lw-j-grid"><span className="lw-j-label">Learner’s Total Mark:</span><span className="lw-j-control">{field("total-mark","Learner total mark")}</span><span className="lw-j-label">Requirements met</span><span className="lw-j-control lw-j-check"><Tick id="requirements-met" label="Requirements met" values={values} onChange={onChange}/></span><span className="lw-j-label">Requirements not met</span><span className="lw-j-control lw-j-check"><Tick id="requirements-not-met" label="Requirements not met" values={values} onChange={onChange}/></span><span className="lw-j-label">Action/s required:</span><span className="lw-j-control">{field("actions-required","Actions required")}</span><span className="lw-j-label" /><span className="lw-j-control" /><span className="lw-j-label">By when:</span><span className="lw-j-control">{field("actions-date","Actions due date","date")}</span></div></div><div className="lw-bar">LEARNER FEEDBACK &amp; COMMENTS</div><Lines id="learner-feedback" count={4} label="Learner feedback and comments" values={values} onChange={onChange}/><div className="lw-bar">DECLARATION BY THE FACILITATOR</div><p>I, {field("facilitator-declaration-name","Facilitator name")}, hereby certify that I have examined the learner workbook and am satisfied with the evidence provided by the learner.</p><div className="lw-bar">DECLARATION BY LEARNER</div><p>I, {field("learner-final-name","Learner name")}, declare that I am satisfied that the feedback given to me was relevant, sufficient and constructive. I accept the assessment judgment and have no further questions relating to this assessment event.</p><table className="lw-table lw-sign"><tbody><tr><th>Learner</th><td>{field("learner-final-signature","Learner signature")}</td><th>Date</th><td>{field("learner-final-date","Learner date","date")}</td><th>Facilitator</th><td>{field("facilitator-final-signature","Facilitator signature")}</td><th>Date</th><td>{field("facilitator-final-date","Facilitator date","date")}</td></tr></tbody></table><div className="lw-bar">DECLARATION BY THE ASSESSOR</div><p>I, {field("assessor-name","Assessor name")}, hereby certify that I have examined the learner workbook and am satisfied with the Facilitator Judgment of this assessment.</p><table className="lw-table lw-sign"><tbody><tr><th>Assessor</th><td>{field("assessor-signature","Assessor signature")}</td><th>Date</th><td>{field("assessor-date","Assessor date","date")}</td><th>Moderator</th><td>{field("moderator-signature","Moderator signature")}</td><th>Date</th><td>{field("moderator-date","Moderator date","date")}</td></tr></tbody></table></Page>
  </div>;
}
