// Shared slide content for the four US 114051 deck sets — one deck per
// Specific Outcome, mirroring how US 114050 ships four lesson decks.
// Built from the full learner-manual source for US 114051.
// Consumed by make-114051-ppt.mjs (PPTX) and make-114051-pdf.ts (PDF).

export const UNIT_FOOT = "US 114051 · Conduct a technical practitioners meeting · NQF 5 · 4 credits";

export const DECKS = [
  /* ================================================================
     DECK 1 — SO 1 · Knowledge of technical practitioners meetings
     ================================================================ */
  {
    file: "US-114051-L1-Knowledge-of-Meetings",
    deckName: "SO 1 — Knowledge of Technical Meetings",
    title: "US 114051 — Knowledge of Technical Practitioners Meetings",
    slides: [
      {
        type: "cover",
        pill: "US 114051 · SO 1 · NQF LEVEL 5 · 4 CREDITS",
        title: "Knowledge of Technical Practitioners Meetings",
        subtitle: "What meetings are for, the types organisations hold, leadership styles, decision-making processes, resolutions and the conventions that keep meetings fair",
        icon: "people",
        meta: [
          ["TIME", "90-minute lessons · Self & Group"],
          ["SESSION", "Friday, 4 Sep 2026 · 09h00 – 14h00"],
          ["MODULE", "Module 1 · Personal Development"],
          ["QUALITY ASSURANCE", "QCTO / MICT SETA"],
        ],
      },
      {
        type: "cards",
        eyebrow: "Specific outcome 1 & assessment criteria",
        title: "What you must be able to demonstrate",
        intro: "Demonstrate knowledge of different types of technical practitioners meetings. You will be assessed against these criteria:",
        cols: 3,
        rowH: 2.15,
        y: 2.1,
        items: [
          { icon: "briefcase", text: "Meeting types & uses", d: "Contract meetings, technical review meetings and project review meetings." },
          { icon: "people", text: "Leadership styles", d: "Democratic, autocratic and facilitative meeting procedures." },
          { icon: "check", text: "Decision-making processes", d: "Voting, consensus, criteria-based rating, ranking, paired comparisons." },
          { icon: "pen", text: "Meeting conventions", d: "Moving, seconding, amending and voting procedures." },
          { icon: "book", text: "The note taker", d: "Why the note taker requires a technical background." },
          { icon: "target", text: "Why it matters", d: "Meetings are where technical teams decide, plan and stay accountable." },
        ],
      },
      {
        type: "bullets",
        eyebrow: "Introduction",
        title: "What do we use meetings for?",
        y: 1.7,
        items: [
          "Meetings are very important for the work of any organisation — good meetings support collective decision-making, planning and follow-up, accountability and democracy.",
          "Used correctly, meetings help an organisation to be efficient. Used badly, they stop serving their purpose: too many long meetings that discuss the same thing over and over without moving forward.",
          "Meetings can become places where conflict is played out — and some people see attending meetings as working for the organisation, instead of a tool for getting work done.",
          "Aim for democratic, constructive participation and involvement from every member.",
          "The principal activities of a technical committee are the development and maintenance of its standards, technical reports and data files, in accordance with the purpose of the organisation.",
        ],
      },
      {
        type: "bullets",
        eyebrow: "Introduction",
        title: "The purpose of a meeting",
        y: 1.7,
        items: [
          "Most people do not like attending meetings — especially when they are not sure what the purpose is, or when the meeting goes on too long and achieves too little.",
          "Meetings must not be too frequent or held just for the sake of it — there must be a need for a meeting.",
          "Decide on the different types of meetings needed: some meetings discuss policy, others discuss organisation (practical work).",
          "Wherever possible, members must know what type of meeting they are going to and what it is for — the PURPOSE of the meeting.",
          "Sometimes an organisation calls a special or extraordinary meeting — planning should take account of the meeting type.",
        ],
      },
      {
        type: "cards",
        eyebrow: "Types of meetings",
        title: "The meetings most organisations hold",
        cols: 2,
        rowH: 2.15,
        y: 1.7,
        items: [
          { icon: "people", text: "General members meeting", d: "The most common — monthly or every two weeks. Members are informed of developments, involved in decisions, and the executive reports on work done. This is where decisions are made." },
          { icon: "target", text: "Special meetings", d: "Called to discuss specific issues — e.g. preparing for a conference or planning the year. Not run like general meetings: they focus only on the issue they were called for." },
          { icon: "briefcase", text: "Executive meetings", d: "Meet more regularly, with a business-like focus: plan implementation, monitor work, deal with problems, watch income and expenditure, and plan the next general meeting." },
          { icon: "award", text: "Annual General Meeting", d: "Laid down in the constitution. The executive accounts for the year's activities and finances, and new leaders are elected with a mandate for the next year." },
        ],
      },
      {
        type: "twocol",
        eyebrow: "Types of meetings",
        title: "The AGM needs two detailed reports",
        left: {
          label: "THE SECRETARY'S REPORT",
          items: [
            "The plans of the organisation for the year",
            "The actual activities that took place",
            "The achievements of the year",
            "The problems experienced",
          ],
        },
        right: {
          label: "THE TREASURER'S REPORT",
          items: [
            "All income — subscriptions, grants, donations, fundraising",
            "All expenditure for the year",
            "The balance, and where that balance is held",
            "Put the main headings on news-prints and explain it in less financial language",
          ],
        },
      },
      {
        type: "cards",
        eyebrow: "Types of technical practitioners meetings",
        title: "Three technical meetings you must know",
        intro: "For technical practitioners, three key meeting types are most relevant:",
        cols: 3,
        rowH: 2.9,
        y: 2.2,
        items: [
          { icon: "briefcase", text: "Contract meetings", d: "Discuss, review and manage contractual obligations and deliverables related to technical projects or services." },
          { icon: "search", text: "Technical review meetings", d: "Evaluate technical solutions, designs and implementations, and resolve technical issues and problems." },
          { icon: "chart", text: "Project review meetings", d: "Assess project progress, timelines, resource allocation and project deliverables." },
        ],
      },
      {
        type: "table",
        eyebrow: "Types of technical practitioners meetings",
        title: "Which meeting, when?",
        header: ["Meeting", "Typical use", "Example"],
        colW: [3.0, 5.0, 4.23],
        rowH: 0.62,
        y: 1.95,
        rows: [
          ["Contract meeting", "Negotiate or review a contract, SLA or deliverable with a client or supplier", "Quarterly SLA review with the support vendor"],
          ["Technical review", "Evaluate a design, system or implementation against requirements and standards", "Design review before a network upgrade"],
          ["Project review", "Track progress, risks, resources and milestones on a running project", "Month-end review of the LAN rollout project"],
        ],
      },
      {
        type: "cards",
        eyebrow: "Leadership styles",
        title: "Who decides — the chair, the group, or both?",
        intro: "Various styles are used to ensure the outcome of the meeting is achieved — different outcomes require different commitment and involvement from participants:",
        cols: 3,
        rowH: 3.0,
        y: 2.15,
        items: [
          { icon: "people", text: "Democratic", d: "Held with appointed or nominated delegates from departments, organisations or areas. Delegates are given the information and all members have a voice in decision-making." },
          { icon: "person", text: "Autocratic", d: "Hosted and led by a chairperson who runs the entire meeting and gives most of the input. Attendees give input only when instructed." },
          { icon: "chat", text: "Facilitative", d: "A group effort — the leader sets a trend of ensuring all members actively participate in the meeting to achieve the outcome or goal." },
        ],
      },
      {
        type: "table",
        eyebrow: "Leadership styles",
        title: "Matching the style to the meeting",
        header: ["Style", "Who decides", "Best when"],
        colW: [2.6, 4.4, 5.23],
        rowH: 0.62,
        y: 1.95,
        rows: [
          ["Democratic", "The members, by discussion and vote", "Decisions need buy-in from every department or area represented"],
          ["Autocratic", "The chairperson", "Time is critical, or one accountable owner must direct the outcome"],
          ["Facilitative", "The group, guided by a neutral facilitator", "Ideas and problem-solving matter more than a formal ruling"],
        ],
      },
      {
        type: "cards",
        eyebrow: "Decision-making processes",
        title: "Five ways meetings reach a decision",
        cols: 3,
        rowH: 2.3,
        y: 1.75,
        items: [
          { icon: "check", text: "Voting", d: "Each participant votes; the option with the most votes wins — simple majority (50% + 1) or supermajority (two-thirds or 75%)." },
          { icon: "people", text: "Consensus", d: "Discussion and compromise until all participants agree or can at least accept the decision." },
          { icon: "chart", text: "Criteria-based rating", d: "Rate each option against predetermined criteria; scores identify the best option." },
          { icon: "layers", text: "Ranking", d: "Rank options best to worst; scores per position are totalled across participants." },
          { icon: "design", text: "Paired comparisons", d: "Compare options two at a time; the option preferred most often is selected." },
          { icon: "target", text: "Match the process", d: "Pick the process that fits the decision's importance, urgency and need for buy-in." },
        ],
      },
      {
        type: "bullets",
        eyebrow: "Decision-making processes",
        title: "Voting in practice — and why consensus first",
        y: 1.7,
        items: [
          "Show of hands: the chairperson calls for hands when opinions differ; votes are counted and the majority decides whether the proposal stands or falls away.",
          "Secret ballot: each person writes their support or objection on paper; votes are counted and the majority decides.",
          "A proposal is usually put forward by one person, seconded by another, and then voted on — if the majority accept it, it becomes binding on the organisation.",
          "It is usually better to reach consensus than to vote: consensus means compromises from everyone, but most people feel part of the decision.",
          "Sometimes a vote is necessary — for example in elections, or when the meeting cannot reach a decision through consensus.",
        ],
      },
      {
        type: "bullets",
        eyebrow: "Decision-making processes",
        title: "Resolutions — formal decisions with three parts",
        y: 1.66,
        items: [
          "Resolutions are formal proposals put to the meeting to agree or disagree with; if passed they become policy of the organisation. Each needs a proposer and a seconder.",
          "NOTING — list the main issues of concern: \u201cThe AGM, meeting on (date), notes the rapid increase in crime in this area and its devastating effects\u2026\u201d",
          "BELIEVING — list the points that show your understanding of the issue and its causes.",
          "THEREFORE RESOLVES — list exactly what the organisation has decided to do or what its policy is on the issue.",
          "Amendments must be accepted by everyone present; if not, a vote is held and the chairperson records those for, against and abstaining. If the majority support the amendment, the original section falls away.",
          "The chairperson and members must study the constitution so they know and understand all these procedures.",
        ],
      },
      {
        type: "cards",
        eyebrow: "Meeting conventions & procedures",
        title: "Order, fairness and effective decisions",
        cols: 2,
        rowH: 1.95,
        y: 1.7,
        items: [
          { icon: "pen", text: "Moving", d: "Formally propose a motion for the meeting to consider." },
          { icon: "person", text: "Seconding", d: "A second member supports the motion — unseconded motions fall away." },
          { icon: "document", text: "Amending", d: "Modify the motion before the vote; amendments are voted on first." },
          { icon: "check", text: "Voting procedures", d: "Show of hands, ballot or poll — counted and recorded by the chair." },
        ],
        callout: { icon: "book", text: "The note taker needs a technical background — minutes must capture the terminology, decisions and reasons accurately." },
      },
      {
        type: "cards",
        eyebrow: "Meeting conventions & procedures",
        title: "Procedural points every member should know",
        intro: "Members use these points to help the chairperson keep the meeting efficient — they should not be over-used just for the sake of it:",
        cols: 3,
        rowH: 2.2,
        y: 2.1,
        items: [
          { icon: "shield", text: "Point of Order", d: "Raised when meeting procedure is not being stuck to — e.g. a speaker is totally off the point — to return the meeting to correct order." },
          { icon: "chat", text: "Point of Information", d: "A member asks to speak out of turn, to request or give more information on the matter being discussed." },
          { icon: "person", text: "Out of Order", d: "The chairperson rules a member out of order for not sticking to procedure, being rude, interjecting or misbehaving." },
          { icon: "check", text: "Protection", d: "A speaker who is being harassed while speaking can ask for the protection of the chairperson." },
          { icon: "people", text: "Quorum", d: "The minimum number of members (set in the constitution) who must be present before the meeting can take decisions — without it, decisions can be forced to be re-discussed." },
          { icon: "target", text: "Use them well", d: "These rules exist to make meetings more efficient and effective — not as weapons." },
        ],
      },
      {
        type: "cards",
        eyebrow: "Now prove it",
        title: "Your work for Specific Outcome 1",
        cols: 3,
        rowH: 2.9,
        y: 2.0,
        items: [
          { icon: "chat", text: "Questioning session", d: "\u201cTypes of meetings, leadership styles and decision processes\u201d — typed answers, AI-marked." },
          { icon: "dashboard", text: "Quizzes 1 & 2", d: "Meeting types & leadership styles · decision-making & conventions. 80%+ is competent." },
          { icon: "book", text: "Gate quizzes", d: "Answer each lesson's gate quiz as you work through lessons 1\u20135 on the Lesson tab." },
        ],
      },
      {
        type: "closing",
        icon: "people",
        quote: "Know the meeting before you run the meeting.",
        text: "General, special, executive and annual general meetings » contract, technical review and project review meetings » democratic, autocratic and facilitative styles » five decision processes » resolutions, conventions and procedural points — the knowledge every chairperson stands on.",
      },
    ],
  },

  /* ================================================================
     DECK 2 — SO 2 · Prepare for a technical practitioners meeting
     ================================================================ */
  {
    file: "US-114051-L2-Preparing-the-Meeting",
    deckName: "SO 2 — Preparing the Meeting",
    title: "US 114051 — Preparing for a Technical Practitioners Meeting",
    slides: [
      {
        type: "cover",
        pill: "US 114051 · SO 2 · NQF LEVEL 5 · 4 CREDITS",
        title: "Preparing for a Technical Practitioners Meeting",
        subtitle: "Venue, facilities, technology and supporting information — documented outcomes, timeous notification and an agenda built the right way",
        icon: "calendar",
        meta: [
          ["TIME", "90-minute lesson · Self & Group"],
          ["SESSION", "Friday, 11 Sep 2026 · 09h00 – 14h00"],
          ["MODULE", "Module 1 · Personal Development"],
          ["QUALITY ASSURANCE", "QCTO / MICT SETA"],
        ],
      },
      {
        type: "cards",
        eyebrow: "Specific outcome 2 & assessment criteria",
        title: "What you must be able to do",
        intro: "Prepare for a technical practitioners meeting. You will be assessed against these criteria:",
        cols: 2,
        rowH: 2.2,
        y: 2.1,
        items: [
          { icon: "globe", text: "Physical arrangements", d: "Venue selection, facilities, technology required and relevant supporting information — relevant to the type of meeting." },
          { icon: "target", text: "Documented outcomes", d: "The intended outcomes of the meeting are clear, concise and well documented." },
          { icon: "calendar", text: "Timeous invitations", d: "Meeting invitations are extended to relevant participants timeously." },
          { icon: "pen", text: "Agenda distributed", d: "The agenda and other supporting documentation are completed and distributed." },
        ],
      },
      {
        type: "cards",
        eyebrow: "Prepare the meeting",
        title: "Physical arrangements — nothing left to chance",
        intro: "The outcome of a meeting is heavily dependent on the preparation and input into it. Four arrangements must be in place:",
        cols: 2,
        rowH: 2.3,
        y: 2.05,
        items: [
          { icon: "globe", text: "Venue selection", d: "Size and interactive capability affect the outcome: participants who must move between groups need the space for it. The venue must be accessible, and located where participants will not be distracted." },
          { icon: "folder", text: "Facilities", d: "Driven by the meeting type, the outcome required and the resources used. Where resources need extra facilities, arrange their availability in advance." },
          { icon: "dashboard", text: "Technology", d: "If delegates must work online, the venue needs internet access; any equipment participants must use has to be made available — and tested." },
          { icon: "document", text: "Support information", d: "User guides and additional information gathered by the organisation must be readily available to the presenter and participants." },
        ],
      },
      {
        type: "bullets",
        eyebrow: "Prepare the meeting",
        title: "Notification — make the meeting easy to attend",
        y: 1.7,
        items: [
          "It is the organisers' responsibility to ensure everyone is notified of the date, time and venue of the meeting, as well as the main issues to be discussed.",
          "A consistent meeting day, time and location — e.g. the first Friday of the month in the same room — helps people make it a habit and cuts notification costs.",
          "Choose a space private enough for strong disagreements, where only the members of the group will be while you are using it.",
          "Make sure the room is open and set up properly: enough chairs, seating in a circle, and the chairperson seated where everyone is visible.",
          "The outcomes of the meeting must be outlined in the invitation, with the requirements of the meeting — sent out timeously so participants can prepare themselves accordingly.",
        ],
      },
      {
        type: "twocol",
        eyebrow: "Prepare the meeting",
        title: "Outcomes and invitations",
        left: {
          label: "DOCUMENT THE OUTCOMES",
          items: [
            "Intended outcomes are clear, concise and well documented",
            "Participants understand what is expected of them — and in which format it must be returned",
            "The agenda is built around the outcomes",
            "Afterwards, success is measured against the outcomes",
          ],
        },
        right: {
          label: "INVITE TIMEOUSLY",
          items: [
            "Include date, time, venue, purpose and the meeting's outcomes",
            "Send early enough for participants to prepare and study the documentation",
            "Schedules can be arranged so the right people attend",
            "Confirm attendance and arrange stand-ins where needed",
          ],
        },
      },
      {
        type: "bullets",
        eyebrow: "Prepare the meeting",
        title: "Preparing the agenda",
        y: 1.66,
        items: [
          "The agenda is a list of the most important issues for the members to discuss — the responsibility of the chairperson and the secretary.",
          "It is drawn from the Matters Arising of the previous meeting: tasks needing a report-back, matters that needed further information, and matters deferred to this meeting. The chairperson reads the previous minutes to prepare.",
          "Arrange items in order of priority and allocate time for each discussion; familiarise yourself with each area of discussion.",
          "An agenda gives people time to plan, do assignments and bring the necessary information — it can be printed and distributed in advance, or written up where everyone can see it.",
          "It is not set in stone: additions can be discussed and approved at the start, and the chair may set a maximum time per topic if there is a lot to get through.",
          "The last item is General / Any Other Business — for short items not included on the agenda.",
        ],
      },
      {
        type: "table",
        eyebrow: "Prepare the meeting",
        title: "The standard agenda",
        intro: "An agenda should include all of the following items that apply to your group:",
        header: ["#", "Agenda item"],
        colW: [1.0, 11.23],
        rowH: 0.55,
        y: 2.05,
        rows: [
          ["1", "Additions to and approval of the agenda"],
          ["2", "Reading, corrections and approval of the previous meeting's minutes"],
          ["3", "Announcements and correspondence to be dealt with"],
          ["4", "Treasurer's report"],
          ["5", "Committee reports"],
          ["6", "Unfinished business — issues left over from previous meetings"],
          ["7", "New business — then General / Any Other Business"],
        ],
      },
      {
        type: "cards",
        eyebrow: "Now prove it",
        title: "Your work for Specific Outcome 2",
        cols: 3,
        rowH: 2.9,
        y: 2.0,
        items: [
          { icon: "chat", text: "Questioning session", d: "\u201cPreparing for a technical practitioners meeting\u201d — typed answers, AI-marked." },
          { icon: "dashboard", text: "Quiz 3", d: "Preparing and chairing the meeting. 80%+ is competent." },
          { icon: "folder", text: "Meeting portfolio", d: "Draft the notice, agenda and invitations for the meeting you will chair — logbook evidence." },
        ],
      },
      {
        type: "closing",
        icon: "calendar",
        quote: "A meeting is won before it starts.",
        text: "Venue » facilities » technology » support information » outcomes outlined in the invitation » timeous notification » an agenda in priority order with time per item — preparation turns meeting time into decision time.",
      },
    ],
  },

  /* ================================================================
     DECK 3 — SO 3 · Chair a technical practitioners meeting
     ================================================================ */
  {
    file: "US-114051-L3-Chairing-the-Meeting",
    deckName: "SO 3 — Chairing the Meeting",
    title: "US 114051 — Chairing a Technical Practitioners Meeting",
    slides: [
      {
        type: "cover",
        pill: "US 114051 · SO 3 · NQF LEVEL 5 · 4 CREDITS",
        title: "Chairing a Technical Practitioners Meeting",
        subtitle: "Rules the members own, the agenda followed step by step, everyone participating — and clear decisions with owners and timeframes",
        icon: "presenter",
        meta: [
          ["TIME", "90-minute lesson · Self & Group"],
          ["SESSION", "Friday, 11 Sep 2026 · 09h00 – 14h00"],
          ["MODULE", "Module 1 · Personal Development"],
          ["QUALITY ASSURANCE", "QCTO / MICT SETA"],
        ],
      },
      {
        type: "cards",
        eyebrow: "Specific outcome 3 & assessment criteria",
        title: "What you must be able to do",
        intro: "Chair a technical practitioners meeting. You will be assessed against these criteria:",
        cols: 3,
        rowH: 2.15,
        y: 2.1,
        items: [
          { icon: "pen", text: "Establish rules", d: "The chair and members agree on rules and guidelines on behaviour." },
          { icon: "check", text: "Apply conventions", d: "Agreed conventions applied throughout, per the standing procedures of the organisation." },
          { icon: "document", text: "Follow the agenda", d: "The published agenda is followed item by item." },
          { icon: "people", text: "Enable participation", d: "Active participation by all members to avoid or minimise conflict." },
          { icon: "clock", text: "Prioritise & time-box", d: "Topics prioritised; discussion time allocated by importance, urgency and complexity." },
          { icon: "target", text: "Land clear decisions", d: "Decisions clear, accurate, time-framed and within the meeting's mandate." },
        ],
      },
      {
        type: "bullets",
        eyebrow: "Chair the meeting",
        title: "The chairperson — the most important person in the room",
        y: 1.7,
        items: [
          "The chairperson sets the pace, keeps people on the topics, ensures democratic decisions are taken and that everyone is on board with them.",
          "Chairing is a great skill: teach members to chair and rotate the job so more people practise it — but use an experienced chairperson for important meetings.",
          "A good chairperson is an ACTIVE chairperson — not just keeping a list of speakers and letting them talk one after the other.",
          "Introduce each topic clearly and guide the discussion, especially when people start repeating points.",
          "When a discussion throws up opposing views, summarise the different positions and propose a way forward: a vote, a further discussion at another date, or a compromise most people can agree with.",
          "Ask the meeting to agree on the way forward — and apologise to those who still wanted to speak.",
        ],
      },
      {
        type: "twocol",
        eyebrow: "Chair the meeting",
        title: "Open with rules the members own",
        left: {
          label: "ESTABLISH RULES & GUIDELINES",
          items: [
            "Agree the rules in conjunction with the members at the start",
            "Set a cut-off time everyone agrees on — it encourages people to be brief",
            "How to get the floor, how long contributions may run",
            "How decisions will be taken — and what is in scope",
            "Agreed rules create buy-in and prevent procedural disputes",
          ],
        },
        right: {
          label: "APPLY THE AGREED CONVENTIONS",
          items: [
            "Run motions through moving, seconding and amending",
            "Follow the published agenda item by item",
            "Handle points of order, information and protection fairly",
            "Park unrelated issues and keep an eye on the clock",
            "The same rules for everyone — applied consistently",
          ],
        },
      },
      {
        type: "bullets",
        eyebrow: "Chair the meeting",
        title: "Running the agenda step by step",
        y: 1.66,
        items: [
          "Open the meeting, welcome everyone and check who is present — record apologies, and send round an attendance register if the group is large.",
          "Start on time, and make sure everyone knows who everyone else is — a quick go-round of names for newcomers.",
          "Minutes: circulate or read the previous meeting's minutes, give members the chance to add what was left out, and adopt them as an accurate record.",
          "Matters arising: work through the points from the previous minutes — tasks report back, deferred matters are discussed.",
          "Correspondence: read out or list the letters received, with the chairperson suggesting action on each.",
          "Other items: someone introduces each item as a discussion or a report — a report covers what was completed, the problems, and what still needs to be done.",
          "For each discussion: examine the issue, get everyone's ideas, arrive at a decision, delegate responsibility, and follow up to ensure completion.",
        ],
      },
      {
        type: "bullets",
        eyebrow: "Chair the meeting",
        title: "Basic steps for chairing — decisions that stick",
        y: 1.7,
        items: [
          "Call on individuals to introduce or lead each agenda point, give everyone a chance to speak — and ensure no one dominates the discussion.",
          "Summarise the discussion clearly, restating the ideas and proposals put forward — without repeating everything that was said.",
          "Get agreement on what the decision is, and make sure everyone understands it.",
          "Delegate the duty of carrying out each decision — the responsible person must know exactly what to do, by when, and when to report back.",
          "Ensure everyone takes part in the discussions and the decision-making.",
          "Always set the date for the next meeting before this one ends.",
        ],
      },
      {
        type: "cards",
        eyebrow: "Chair the meeting",
        title: "Facilitation skills that make it work",
        cols: 3,
        rowH: 2.3,
        y: 1.75,
        items: [
          { icon: "chat", text: "Encourage discussion", d: "Turn questions back to the group, ask open-ended questions, compliment ideas — let people say \u201cditto\u201d instead of repeating." },
          { icon: "layers", text: "Manage the traffic", d: "Jot down speakers in order; let first-time speakers skip the queue; no second turn until everyone has spoken once." },
          { icon: "shield", text: "Stay neutral", d: "Don't use the chair to impose your own opinions — step aside if you feel strongly, speak last, and mark personal views as personal." },
          { icon: "person", text: "Watch the non-verbals", d: "Look at speakers, lean forward, nod; make eye contact with people who need encouragement — spot the half-raised hand." },
          { icon: "clock", text: "Use silence", d: "Don't fear silence — it gives people a chance to collect their thoughts and often draws out hesitant comments." },
          { icon: "target", text: "Guide to closure", d: "Restate comments, ask for clarification, summarise what is agreed and what is left, and call the decision when it's time." },
        ],
      },
      {
        type: "bullets",
        eyebrow: "Chair the meeting",
        title: "Participation, priorities and staying on course",
        y: 1.7,
        items: [
          "Provide for active participation by ALL members — invite quiet members by name and draw the whole group into the discussion; that is how conflict is minimised.",
          "Prioritise topics and allocate discussion time according to importance, urgency, complexity and the agenda.",
          "If discussion strays off-topic, point it out and redirect it back on course; agree a time limit when a discussion threatens to run away.",
          "If the group is only repeating itself, restate and summarise the issues and ask if people are ready to decide — or table the matter, ask someone to bring more information, or form a committee.",
          "If a decision is too contentious, postpone it to the next meeting so people can think things over — and calm down.",
          "Ensure agreed decisions are clear, accurate, include a time frame for action, and are within the mandate of the type of meeting conducted.",
          "Take time at the end to process: what went well, lingering concerns — and END ON TIME; nothing makes people dread meetings more than overruns.",
        ],
      },
      {
        type: "table",
        eyebrow: "Chair the meeting",
        title: "Managing difficult behaviours",
        header: ["Behaviour", "What the chair does"],
        colW: [3.6, 8.63],
        rowH: 0.62,
        y: 1.75,
        rows: [
          ["The heckler", "Aggressive and argumentative — stay calm, find merit in one point, express agreement, move on."],
          ["The one who won't shut up", "Eager-beaver, show-off, well-informed or just talkative — wait for a breath, thank them, ask to hear from someone else; toss misstatements back to the group."],
          ["The cynic", "May gripe at random or have a real complaint — point out the meeting seeks better ways by constructive cooperation; let a group member answer."],
          ["The silent one", "Bored, shy or uncertain — ask directly for their opinion, show respect for their experience, encourage their first contribution; never force them."],
          ["The egos", "Personalities clash — compliment their enthusiasm, ask for constructive solutions, emphasise points they agree on, throw a question to the rest."],
          ["The chatty couple", "Side conversations — remind them of the debate, draw them back with an easy question and a recap of what was just discussed."],
          ["The one who is defiantly wrong", "Confused or misinformed — tactfully restate their point to show the error, or leave the debate open for the group to correct it."],
        ],
      },
      {
        type: "cards",
        eyebrow: "Now prove it",
        title: "Your work for Specific Outcome 3",
        cols: 3,
        rowH: 2.9,
        y: 2.0,
        items: [
          { icon: "presenter", text: "Chair a meeting", d: "Role-play practical: chair a 10-minute technical meeting from a scenario card — observed evidence." },
          { icon: "chat", text: "Questioning session", d: "\u201cChairing a technical practitioners meeting\u201d — typed answers, AI-marked." },
          { icon: "dashboard", text: "Quiz 3", d: "Preparing and chairing the meeting. 80%+ is competent." },
        ],
      },
      {
        type: "closing",
        icon: "presenter",
        quote: "Run the meeting — don't let the meeting run you.",
        text: "Rules agreed with the members » the agenda followed step by step » everyone heard, no one dominating » difficult behaviour managed with skill » decisions that are clear, accurate, time-framed — and a meeting that ends on time.",
      },
    ],
  },

  /* ================================================================
     DECK 4 — SO 4 · Post-meeting follow-up
     ================================================================ */
  {
    file: "US-114051-L4-Post-Meeting-Follow-Up",
    deckName: "SO 4 — Post-Meeting Follow-Up",
    title: "US 114051 — Post-Meeting Follow-Up for a Technical Meeting",
    slides: [
      {
        type: "cover",
        pill: "US 114051 · SO 4 · NQF LEVEL 5 · 4 CREDITS",
        title: "Post-Meeting Follow-Up for a Technical Meeting",
        subtitle: "Accurate minutes in line with organisational policy, decisions communicated on time — and an implementation stage that actually delivers",
        icon: "document",
        meta: [
          ["TIME", "90-minute lesson · Self & Group"],
          ["SESSION", "Friday, 11 Sep 2026 · 09h00 – 14h00"],
          ["MODULE", "Module 1 · Personal Development"],
          ["QUALITY ASSURANCE", "QCTO / MICT SETA"],
        ],
      },
      {
        type: "cards",
        eyebrow: "Specific outcome 4 & assessment criteria",
        title: "What you must be able to do",
        intro: "Conduct post-meeting follow-up: circulation of minutes, recommendations, motions passed and feedback. The assessment criteria:",
        cols: 3,
        rowH: 2.9,
        y: 2.1,
        items: [
          { icon: "document", text: "Accurate minutes", d: "Minutes are produced accurately and in line with the policy of the organisation." },
          { icon: "chat", text: "Decisions communicated", d: "Agreed records of discussion reach interested parties in the format and time frame the meeting type and organisation require." },
          { icon: "check", text: "Actions summarised", d: "A summary of discussions and actions that meets format requirements." },
        ],
      },
      {
        type: "bullets",
        eyebrow: "Post-meeting follow-up",
        title: "Why minutes matter",
        y: 1.7,
        items: [
          "Minutes form a historical record of a group's work — a record of decisions and details when people's memories fail or when they disagree.",
          "They remind people of assignments they have taken on and the deadlines they need to meet.",
          "They inform those not present of what happened at the meeting.",
          "They give future members a way to build on past successes and avoid reinventing the wheel.",
          "Accurate minutes prevent arguments about previous decisions — and are the guide for drawing up the next agenda and the annual report.",
        ],
      },
      {
        type: "cards",
        eyebrow: "Post-meeting follow-up",
        title: "Taking good minutes — three skills",
        cols: 3,
        rowH: 3.0,
        y: 1.8,
        items: [
          { icon: "person", text: "1 · Listening", d: "Not just hearing what is said — making sure you understand it. The note taker's technical background earns its keep here." },
          { icon: "pen", text: "2 · Taking notes", d: "Write only the main points and the decisions, in your own words. Pay special attention to decisions — ask for them to be repeated, and stop the meeting if anything is unclear." },
          { icon: "document", text: "3 · Writing the minutes", d: "Neatly, in a dedicated minute book or file — never on scraps of paper — kept safe and available for consultation at any time." },
        ],
        note: "Separate fact from opinion: attribute views to their source — \u201cJane suggested that\u2026\u201d, \u201cthe group concluded that\u2026\u201d.",
      },
      {
        type: "table",
        eyebrow: "Post-meeting follow-up",
        title: "What the minutes must contain",
        header: ["Section", "Contents"],
        colW: [3.6, 8.63],
        rowH: 0.55,
        y: 1.8,
        rows: [
          ["Header", "Nature of the meeting, date, time and place — and who took the minutes"],
          ["Attendance", "Everyone present, visitors, apologies and absentees; time the meeting was called to order"],
          ["Previous minutes", "Approval of the previous meeting's minutes, with any corrections or amendments"],
          ["Reports", "Summary of reports, announcements and other information shared"],
          ["Motions & resolutions", "Recorded verbatim with mover and seconder, and read back in the meeting to confirm accuracy"],
          ["Decisions & actions", "Key points of each discussion, decisions reached, who took each assignment and its deadline"],
          ["Closure", "Time of adjournment — and the next meeting's date, time and location"],
        ],
      },
      {
        type: "bullets",
        eyebrow: "Post-meeting follow-up",
        title: "After the meeting — close the loop",
        y: 1.7,
        items: [
          "Write up, organise and distribute the minutes to everyone who attended within a reasonable time — distributing them before the next meeting reminds people of assignments and deadlines.",
          "Communicate the agreed records of discussion to interested parties in the format and time frame required — contractual, technical review or project specific.",
          "Follow up with people: thank them for their input and make sure they understand their assignments and have what they need.",
          "Corrections or additions are recorded in the next meeting's minutes, and the group approves the minutes as accurate — as read or as amended.",
          "Then start getting ready for the next meeting.",
        ],
      },
      {
        type: "cards",
        eyebrow: "Post-meeting follow-up",
        title: "The decision meeting life cycle",
        intro: "Decision meetings are not isolated events — they are part of a continuous cycle, and each stage can be face-to-face or distributed, synchronous or asynchronous:",
        cols: 3,
        rowH: 2.6,
        y: 2.15,
        items: [
          { icon: "calendar", text: "Pre-meeting", d: "Create the agenda, identify the people to invite and their roles, prepare each participant, include background information." },
          { icon: "people", text: "Meeting", d: "Interactions among participants conclude with one or more decisions to be implemented afterwards." },
          { icon: "trend", text: "Post-meeting", d: "Dissemination, monitoring the implementation of decisions, and clarifying ambiguous decision details — often by people who weren't in the room." },
        ],
        note: "The gap between the end of a meeting and its implementation can turn a decision inconsequent — decisions implemented without follow-up produce outcomes different from those planned.",
      },
      {
        type: "cards",
        eyebrow: "Post-meeting follow-up",
        title: "Four aspects of post-meeting support",
        cols: 2,
        rowH: 2.2,
        y: 1.75,
        items: [
          { icon: "document", text: "1 · Implementation plan", d: "Draft and publish an execution plan for each decision; allow changes during execution; generate tasks for the implementation team and record completed tasks." },
          { icon: "check", text: "2 · Follow-up of activities", d: "A formal link between each meeting outcome and its implementation — working steps whose execution can be tracked and corrected." },
          { icon: "chat", text: "3 · Means of interaction", d: "A structured, persistent communication channel between decision makers and implementers — an extension of the meeting for resolving ambiguities." },
          { icon: "globe", text: "4 · Awareness", d: "Filtered progress information for people affected by the decision — subscriptions and notifications avoid the informal demands that waste time." },
        ],
      },
      {
        type: "bullets",
        eyebrow: "Post-meeting follow-up",
        title: "What structured follow-up buys you",
        y: 1.8,
        items: [
          "A structured follow-up of the decisions made at the meeting — decisions stop getting lost on the way to implementation.",
          "Explicit awareness of task progress for every involved role — including management and affected outsiders.",
          "Organisational memory: potentially valuable information is captured and can be consulted at any time, helping avoid recurrent mistakes.",
          "Easier identification of issues for the next cycle: unclear details of decisions just made and unsettled issues after tasks are done.",
          "Formal definition of responsibilities and expected results — with less meeting time spent on follow-up chores.",
        ],
      },
      {
        type: "cards",
        eyebrow: "Now prove it",
        title: "Your work for Specific Outcome 4",
        cols: 3,
        rowH: 2.9,
        y: 2.0,
        items: [
          { icon: "chat", text: "Questioning session", d: "\u201cPost-meeting follow-up\u201d — typed answers, AI-marked." },
          { icon: "dashboard", text: "Quiz 4 & self assessment", d: "Post-meeting follow-up quiz, then the honest tick-box self assessment." },
          { icon: "folder", text: "Logbook — Meeting portfolio", d: "Notice and agenda, invitations, attendance register, minutes and action summary. Mark it 114051." },
        ],
      },
      {
        type: "closing",
        icon: "document",
        quote: "The meeting is not over when it ends.",
        text: "Minutes that stand as the record » decisions communicated in format and on time » an implementation plan with owners, tracking and awareness — follow-up is what turns discussion into delivery.",
      },
    ],
  },
];
